
#pragma once

#include <assert.h>

#ifndef ASSERT
#define ASSERT assert 
#endif // ASSERT

// define the command header...
typedef struct {
	int   m_pkg_len;    // body size...
	int   m_type;       // client type...
	int   m_cmd;        // command id...
	int   m_sock;       // php sock in transmit...
} Cmd_Header;
